AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy AWS Config Rules for DynamoDB
Parameters:
  ConfigRuleName1:
    Type: String
    Default: dynamodb-table-encryption-enabled
    Description: The name that you assign to the AWS Config rule for dynamodb-table-encryption-enabled.
    MinLength: '1'
    ConstraintDescription: This parameter is required.
Resources:
  AWSConfigRuleForDDB:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: !Ref 'ConfigRuleName1'
      Description: Checks whether the Amazon DynamoDB tables are encrypted and checks their status. The rule is compliant if the status is enabled or enabling.
      Scope:
        ComplianceResourceTypes:
          - AWS::DynamoDB::Table
      Source:
        Owner: AWS
        SourceIdentifier: DYNAMODB_TABLE_ENCRYPTION_ENABLED